import Head from 'next/head'

import HomeView from '../views/home'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Next.js w/z WebGL2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeView />
    </div>
  )
}

export default Home
